name: VLTest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.00301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b20000'
    - '#00468b'
    - '#458c00'
    - '#c36d6f'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
